variable "ENV" {
  default = "production"
}

variable "aws_region" {
  default = "us-east-1"
}

variable "TAG" {
  description = "TAG version used for the task definition. This is available as a environment variable"
}

variable "APP_NAME_HASH" {
  description = "Application name. This value needs to be defined as an environment variable "
}

variable "APP_ENV" {
  description = "Environment where the application will be deploy. This values needs to be defined as an environment variable"
}

variable "APP_ORG_HASH" {
  description = "Hash that identify the Organization"
}

variable "ecr_nginx_repo" {
  default = "xtages-nginx"
  description = "ECR repository that host our nginx version"
}

variable "nginx_version" {
  default = "1.18.0"
  description = "Nginx version that will be pulled from ECR nginx repo using that tag name"
}

variable "HOST_HEADER" {
  description = "customer URL in case it's hosting their app"
  default = ""
}

variable "CUSTOMER_DOMAIN" {
  description = "customer domain that we'll add to the LB listener"
  default = ""
}

variable "APP_BUILD_ID" {
  description = "Build id generated by Console to identify the deployment"
}

variable "BACKEND_BUCKET" {
  description = "S3 bucket where the Terraform state will be stored"
}

variable "PLAN_PAID" {
  description = "True if the plan is a paid one False if the plan is a free one"
  type = bool
}
